Changed the init script
The previous one contained references to password

diff --git a/templates/default/redis_init.erb b/templates/default/redis_init.erb
--- a/templates/default/redis_init.erb
+++ b/templates/default/redis_init.erb
@@ -1,38 +1,29 @@
-#!/bin/sh
-#
-# redis-<%= @name %>     Start redis-<%= @name %>
-#
-# chkconfig: 2345 08 92
-# description:
-# Simple Redis init.d script conceived to work on Linux systems
-# as it does use the /proc filesystem.
-#
-# config: /etc/redis/<%= @name %>.conf
-#
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides: redis-<%= @name %>
-# Required-Start:
-# Required-Stop:
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
-# Short-Description: start and stop redis-<%= @name %>
-# Description: Start, stop redis-<%= @name %>
+# Provides:		redis-server
+# Required-Start:	$syslog $remote_fs
+# Required-Stop:	$syslog $remote_fs
+# Should-Start:		$local_fs
+# Should-Stop:		$local_fs
+# Default-Start:	2 3 4 5
+# Default-Stop:		0 1 6
+# Short-Description:  <%= @name %> - Persistent key-value db
+# Description:	<%= @name %> - Persistent key-value db
 ### END INIT INFO
 
 
-REDISPORT=<%= @port %>
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=<%= node.redis.dst_dir %>/bin/redis-server
+DAEMON_ARGS="<%= @conf_dir %>/<%= @name %>.conf"
+NAME=redis-server
+DESC=redis-server
 
-<% if node.redis.install_type == "source" %>
-EXEC=<%= node.redis.dst_dir %>/bin/redis-server
-CLIEXEC=<%= node.redis.dst_dir %>/bin/redis-cli
-<% else %>
-EXEC=<%= node.redis.dst_dir %>/redis-server
-CLIEXEC=<%= node.redis.dst_dir %>/redis-cli
-<% end %>
-
-PASSWORD="<%= node.redis.config.requirepass.to_s %>"
+RUNDIR=/var/run/redis
 PIDFILE=<%= @pidfile %>
-CONF="<%= @conf_dir %>/<%= @name %>.conf"
+
+test -x $DAEMON || exit 0
+
+set -e
 
 <% if node.platform_family == "debian" %>
 ulimit -Hn <%= node.redis.ulimit %>
@@ -40,44 +31,50 @@ ulimit -Sn <%= node.redis.ulimit %>
 <% end %>
 
 case "$1" in
-    start)
-        if [ -f $PIDFILE ]
-        then
-                echo "$PIDFILE exists, process is already running or crashed"
-        else
-                <% if @pidfile == "/var/run/redis/redis.pid" %>
-                mkdir -p /var/run/redis
-                chown -R redis:redis /var/run/redis
-                <% end %>
+  start)
+	echo -n "Starting $DESC: "
+	mkdir -p $RUNDIR
+	touch $PIDFILE
+	chown redis:redis $RUNDIR $PIDFILE
+	chmod 755 $RUNDIR
+	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	;;
+  stop)
+	echo -n "Stopping $DESC: "
+	if start-stop-daemon --stop --retry forever/QUIT/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	rm -f $PIDFILE
+	;;
 
-                <% if @logfile.downcase != "stdout" %>
-                chown -R <%= @user %>:<%= @user %> <%= @logfile %>
-                <% end %>
-                echo "Starting Redis server..."
-                sudo -u <%= @user %> $EXEC $CONF
-        fi
-        ;;
-    stop)
-        if [ ! -f $PIDFILE ]
-        then
-                echo "$PIDFILE does not exist, process is not running"
-        else
-                PID=$(cat $PIDFILE)
-                echo "Stopping ..."
-                $CLIEXEC -p $REDISPORT -a "$PASSWORD" shutdown
-                while [ -x /proc/${PID} ]
-                do
-                    echo "Waiting for Redis to shutdown ..."
-                    sleep 1
-                done
-                echo "Redis stopped"
-        fi
-        ;;
-    restart)
-        ${0} stop
-        ${0} start
-        ;;
-    *)
-        echo "Please use start, stop or restart as first argument"
-        ;;
+  restart|force-reload)
+	${0} stop
+	${0} start
+	;;
+
+  status)
+	echo -n "$DESC is "
+	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
+	then
+		echo "running"
+	else
+		echo "not running"
+		exit 1
+	fi
+	;;
+
+  *)
+	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
+	exit 1
+	;;
 esac
+
+exit 0
